/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Manufacturer } from "./Manufacturer";
import { ManufacturerCountArgs } from "./ManufacturerCountArgs";
import { ManufacturerFindManyArgs } from "./ManufacturerFindManyArgs";
import { ManufacturerFindUniqueArgs } from "./ManufacturerFindUniqueArgs";
import { CreateManufacturerArgs } from "./CreateManufacturerArgs";
import { UpdateManufacturerArgs } from "./UpdateManufacturerArgs";
import { DeleteManufacturerArgs } from "./DeleteManufacturerArgs";
import { VehicleFindManyArgs } from "../../vehicle/base/VehicleFindManyArgs";
import { Vehicle } from "../../vehicle/base/Vehicle";
import { ManufacturerService } from "../manufacturer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Manufacturer)
export class ManufacturerResolverBase {
  constructor(
    protected readonly service: ManufacturerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "read",
    possession: "any",
  })
  async _manufacturersMeta(
    @graphql.Args() args: ManufacturerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Manufacturer])
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "read",
    possession: "any",
  })
  async manufacturers(
    @graphql.Args() args: ManufacturerFindManyArgs
  ): Promise<Manufacturer[]> {
    return this.service.manufacturers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Manufacturer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "read",
    possession: "own",
  })
  async manufacturer(
    @graphql.Args() args: ManufacturerFindUniqueArgs
  ): Promise<Manufacturer | null> {
    const result = await this.service.manufacturer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Manufacturer)
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "create",
    possession: "any",
  })
  async createManufacturer(
    @graphql.Args() args: CreateManufacturerArgs
  ): Promise<Manufacturer> {
    return await this.service.createManufacturer({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Manufacturer)
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "update",
    possession: "any",
  })
  async updateManufacturer(
    @graphql.Args() args: UpdateManufacturerArgs
  ): Promise<Manufacturer | null> {
    try {
      return await this.service.updateManufacturer({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Manufacturer)
  @nestAccessControl.UseRoles({
    resource: "Manufacturer",
    action: "delete",
    possession: "any",
  })
  async deleteManufacturer(
    @graphql.Args() args: DeleteManufacturerArgs
  ): Promise<Manufacturer | null> {
    try {
      return await this.service.deleteManufacturer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Vehicle], { name: "vehicles" })
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "read",
    possession: "any",
  })
  async findVehicles(
    @graphql.Parent() parent: Manufacturer,
    @graphql.Args() args: VehicleFindManyArgs
  ): Promise<Vehicle[]> {
    const results = await this.service.findVehicles(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
